format = """
[](#A10518)\
$os\
$username\
[](bg:#B70016 fg:#A10518)\
$directory\
[](fg:#B70016 bg:#E62E00)\
$git_branch\
$git_status\
[](fg:#E62E00 bg:#FF0000)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#FF0000 bg:#FF7777)\
$docker_context\
[](fg:#FF7777)\
$time\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#A10518"
style_root = "bg:#A10518"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#B70016"
disabled = true # Disabled by default

[directory]
style = "bg:#B70016"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#E62E00"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#E62E00"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#E62E00"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "color:#000000"
format = '[ ♥ $time ]($style)'
